languageCode = "en"
languageName = "English"
weight = 1
title = "synaptic_radio"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo.png"
  description = "A sloth like understanding of machine learning."

[params.author]
  name = "Anshuman Sahoo"
  email = "anshuman264@gmail.com"
  image = "anshu_profile.png"
  headline = "ML Research Engineer"
  bio = "Lead R&D Engineer@BenchSci"
  links = [
    { x-twitter = "https://twitter.com/anshuML264" },
    { github = "https://github.com/anshu92" },
  ]