baseURL = 'https://anshu92.github.io/'
languageCode = 'en-us'
title = 'Synaptic Radio'
theme = 'stack'

# Copyright notice
copyright = 'Anshuman Sahoo'

# Params
[params]
mainSections = ['post']
featuredImageField = 'image'
rssFullContent = true
favicon = '/img/brain-logo.png'

# Author configuration
[params.author]
name = 'Anshuman Sahoo'
bio = "I'm Anshu, a machine learning engineer with nine years of experience turning first-principles ideas into prototypes and production systems. Here, I share ideas, practical insights and best practices to help fellow engineers accelerate their ML projects."
email = 'anshuman264@gmail.com'

# Sidebar configuration
[params.sidebar]
emoji = '🎧'
subtitle = "I'm Anshu, a machine learning engineer with nine years of experience turning first-principles ideas into prototypes and production systems. Here, I share ideas, practical insights and best practices to help fellow engineers accelerate their ML projects."
compact = false

# [params.sidebar.avatar]
# enabled = true
# local = true
# src = "img/brain-logo-small.png"

# Article configuration
[params.article]
math = true
readingTime = true
license.enabled = false

# Comments (disabled by default)
[params.comments]
enabled = false

# Widget configuration
[params.widgets]
homepage = [
    { type = "search" },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } }
]
page = [
    { type = "toc" }
]

# Default image
[params.defaultImage]
opengraph.enabled = false
article.enabled = false

# Menu configuration
[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
weight = -100
[[menu.main]]
identifier = 'archives'
name = 'Archives'
url = '/page/archives/'
weight = -90
params = { icon = '' }
[[menu.main]]
identifier = 'categories'
name = 'Categories'
url = '/categories/'
weight = -80
[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = -70

# Social menu configuration
[[menu.social]]
identifier = 'linkedin'
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/anshu92/'
params = { icon = 'brand-linkedin' }

# Related content
[related]
includeNewer = true
threshold = 60
toLower = false
[[related.indices]]
name = 'keywords'
weight = 100
[[related.indices]]
name = 'tags'
weight = 80
[[related.indices]]
name = 'categories'
weight = 60
[[related.indices]]
name = 'date'
weight = 10

# Markup configuration
[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2
[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
style = 'github'
tabWidth = 4
