# .github/workflows/deploy.yml
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.3 # Use a recent EXTENDED Hugo version compatible with Blowfish
    steps:
      - name: Install Hugo CLI (Extended)
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Crucial for fetching the Blowfish theme
          fetch-depth: 0 # Needed for .Lastmod based on Git history
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          # Set base URL dynamically from Pages settings
          HUGO_BASEURL: ${{ steps.pages.outputs.base_url }}
        run: |
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/" # Build site using dynamic base URL
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # Hugo builds to 'public' directory by default

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4